accessToken: sampleaccesstoken
apikey: sampleApikey
apisecret: samplesecret
accessTokenUrl: https://api.upstox.com/index/oauth/token
swagger:
  enabled: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
